using PromptForge.App.Models;

namespace PromptForge.App.Services;

public static class IntentModeCatalog
{
    private static readonly IReadOnlyDictionary<string, IntentModeDefinition> Definitions =
        new Dictionary<string, IntentModeDefinition>(StringComparer.OrdinalIgnoreCase)
        {
            ["Playful Chaos"] = new(
                "Playful Chaos",
                Whimsy: 78,
                Tension: 42,
                Awe: 52,
                Chaos: 74,
                MotionEnergy: 70,
                AtmosphericDepth: 48,
                NarrativeDensity: 58,
                Symbolism: 38,
                Saturation: 72,
                Contrast: 64,
                Lighting: "Golden hour",
                Summary: "buoyant mischief, energetic movement, and controlled disorder"),
            ["Sacred Stillness"] = new(
                "Sacred Stillness",
                Whimsy: 8,
                Tension: 18,
                Awe: 84,
                Chaos: 6,
                MotionEnergy: 10,
                AtmosphericDepth: 78,
                NarrativeDensity: 46,
                Symbolism: 72,
                Saturation: 42,
                Contrast: 50,
                Lighting: "Soft daylight",
                Summary: "reverent calm, contemplative atmosphere, and quiet grandeur"),
            ["Dramatic Fracture"] = new(
                "Dramatic Fracture",
                Whimsy: 6,
                Tension: 86,
                Awe: 58,
                Chaos: 68,
                MotionEnergy: 62,
                AtmosphericDepth: 60,
                NarrativeDensity: 66,
                Symbolism: 54,
                Saturation: 48,
                Contrast: 82,
                Lighting: "Dramatic studio light",
                Summary: "emotional rupture, cinematic strain, and unstable force"),
            ["Dreamlike Drift"] = new(
                "Dreamlike Drift",
                Whimsy: 34,
                Tension: 26,
                Awe: 74,
                Chaos: 24,
                MotionEnergy: 28,
                AtmosphericDepth: 88,
                NarrativeDensity: 54,
                Symbolism: 78,
                Saturation: 58,
                Contrast: 40,
                Lighting: "Moonlit",
                Summary: "floating surreal calm, soft wonder, and lucid symbolic flow"),
            ["Quiet Wonder"] = new(
                "Quiet Wonder",
                Whimsy: 25,
                Tension: 20,
                Awe: 58,
                Chaos: 12,
                MotionEnergy: 22,
                AtmosphericDepth: 62,
                NarrativeDensity: 38,
                Symbolism: 36,
                Saturation: 46,
                Contrast: 38,
                Lighting: "Soft daylight",
                Summary: "gentle beauty, spacious calm, and restrained uplift"),
            ["Ominous Calm"] = new(
                "Ominous Calm",
                Whimsy: 5,
                Tension: 68,
                Awe: 28,
                Chaos: 22,
                MotionEnergy: 14,
                AtmosphericDepth: 54,
                NarrativeDensity: 48,
                Symbolism: 34,
                Saturation: 24,
                Contrast: 66,
                Lighting: "Overcast",
                Summary: "suspended threat, still air, and restrained severity"),
            ["Mythic Radiance"] = new(
                "Mythic Radiance",
                Whimsy: 10,
                Tension: 34,
                Awe: 88,
                Chaos: 18,
                MotionEnergy: 34,
                AtmosphericDepth: 78,
                NarrativeDensity: 56,
                Symbolism: 74,
                Saturation: 68,
                Contrast: 64,
                Lighting: "Golden hour",
                Summary: "luminous grandeur, iconic scale, and elevated symbolic authority"),
            ["Playful Reverie"] = new(
                "Playful Reverie",
                Whimsy: 62,
                Tension: 18,
                Awe: 44,
                Chaos: 24,
                MotionEnergy: 34,
                AtmosphericDepth: 52,
                NarrativeDensity: 40,
                Symbolism: 38,
                Saturation: 58,
                Contrast: 34,
                Lighting: "Soft glow",
                Summary: "dreamlike charm, tender whimsy, and welcoming strangeness"),
            ["Haunted Stillness"] = new(
                "Haunted Stillness",
                Whimsy: 0,
                Tension: 72,
                Awe: 42,
                Chaos: 16,
                MotionEnergy: 8,
                AtmosphericDepth: 70,
                NarrativeDensity: 44,
                Symbolism: 50,
                Saturation: 18,
                Contrast: 52,
                Lighting: "Moonlit",
                Summary: "ghostly quiet, lingering weight, and restrained eeriness"),
            ["Charged Spectacle"] = new(
                "Charged Spectacle",
                Whimsy: 14,
                Tension: 62,
                Awe: 76,
                Chaos: 52,
                MotionEnergy: 72,
                AtmosphericDepth: 66,
                NarrativeDensity: 52,
                Symbolism: 30,
                Saturation: 72,
                Contrast: 78,
                Lighting: "Dramatic studio light",
                Summary: "theatrical force, kinetic impact, and bold image power"),
            ["Melancholic Drift"] = new(
                "Melancholic Drift",
                Whimsy: 8,
                Tension: 34,
                Awe: 30,
                Chaos: 20,
                MotionEnergy: 18,
                AtmosphericDepth: 68,
                NarrativeDensity: 46,
                Symbolism: 42,
                Saturation: 20,
                Contrast: 28,
                Lighting: "Dusk haze",
                Summary: "soft sorrow, suspended motion, and reflective distance"),
            ["Storybook Tension"] = new(
                "Storybook Tension",
                Whimsy: 44,
                Tension: 56,
                Awe: 48,
                Chaos: 34,
                MotionEnergy: 40,
                AtmosphericDepth: 44,
                NarrativeDensity: 54,
                Symbolism: 46,
                Saturation: 56,
                Contrast: 50,
                Lighting: "Warm directional light",
                Summary: "folkloric peril, readable stakes, and playful dramatic clarity"),
        };

    public static IReadOnlyList<string> Names { get; } = new[]
    {
        "Custom",
        "Playful Chaos",
        "Sacred Stillness",
        "Dramatic Fracture",
        "Dreamlike Drift",
        "Quiet Wonder",
        "Ominous Calm",
        "Mythic Radiance",
        "Playful Reverie",
        "Haunted Stillness",
        "Charged Spectacle",
        "Melancholic Drift",
        "Storybook Tension",
    };

    public static bool TryGet(string? intentMode, out IntentModeDefinition definition)
    {
        if (string.IsNullOrWhiteSpace(intentMode) || string.Equals(intentMode, "Custom", StringComparison.OrdinalIgnoreCase))
        {
            definition = null!;
            return false;
        }

        return Definitions.TryGetValue(intentMode, out definition!);
    }
}
